### ISSUE TITLE
Build Error DST 0.8

### ISSUE THREAD

**Issue by ghost** [cheind/dest#2]
I am trying to build DST 0.8 with following environment
1. Visual Studio 10 (2010) 
2. CMake 3.4.3
3. OpenCV 2.4.9
4. Eigen 3.2.7

Unfortunately I am getting following error.

1>------ Rebuild All started: Project: ZERO_CHECK, Configuration: Debug Win32 ------
1>Build started 3/29/2016 10:37:52 AM.
1>InitializeBuildStatus:
1>  Creating "Win32\Debug\ZERO_CHECK\ZERO_CHECK.unsuccessfulbuild" because "AlwaysCreate" was specified.
1>CustomBuild:
1>  Checking Build System
1>  CMake does not need to re-run because D:/Library/Dest Landmark/CMakeFiles/generate.stamp is up-to-date.
1>FinalizeBuildStatus:
1>  Deleting file "Win32\Debug\ZERO_CHECK\ZERO_CHECK.unsuccessfulbuild".
1>  Touching "Win32\Debug\ZERO_CHECK\ZERO_CHECK.lastbuildstate".
1>
1>Build succeeded.
1>
1>Time Elapsed 00:00:00.04
2>------ Rebuild All started: Project: dest, Configuration: Debug Win32 ------
2>Build started 3/29/2016 10:37:52 AM.
2>InitializeBuildStatus:
2>  Creating "dest.dir\Debug\dest.unsuccessfulbuild" because "AlwaysCreate" was specified.
2>CustomBuild:
2>  Building Custom Rule D:/Library/Dest/dest-0.8/CMakeLists.txt
2>  CMake does not need to re-run because D:\Library\Dest Landmark\CMakeFiles\generate.stamp is up-to-date.
2>ClCompile:
2>  shape.cpp
2>  image.cpp
2>  training_data.cpp
2>..\Dest\dest-0.8\src\core\training_data.cpp(73): warning C4018: '<' : signed/unsigned mismatch
2>..\Dest\dest-0.8\src\core\training_data.cpp(86): error C2039: 'shuffle' : is not a member of 'std'
2>..\Dest\dest-0.8\src\core\training_data.cpp(86): error C3861: 'shuffle': identifier not found
2>..\Dest\dest-0.8\src\core\training_data.cpp(93): warning C4018: '<' : signed/unsigned mismatch
2>  tracker.cpp
2>D:\Library\Dest\dest-0.8\inc\dest/core/regressor.h(63): error C2248: 'std::unique_ptr<_Ty>::operator =' : cannot access private member declared in class 'std::unique_ptr<_Ty>'
2>          with
2>          [
2>              _Ty=dest::core::Regressor::data
2>          ]
2>          C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\memory(2352) : see declaration of 'std::unique_ptr<_Ty>::operator ='
2>          with
2>          [
2>              _Ty=dest::core::Regressor::data
2>          ]
2>          This diagnostic occurred in the compiler generated function 'dest::core::Regressor &dest::core::Regressor::operator =(const dest::core::Regressor &)'
2>  regressor.cpp
2>D:\Library\Dest\dest-0.8\inc\dest/core/tree.h(103): error C2248: 'std::unique_ptr<_Ty>::operator =' : cannot access private member declared in class 'std::unique_ptr<_Ty>'
2>          with
2>          [
2>              _Ty=dest::core::Tree::data
2>          ]
2>          C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\memory(2352) : see declaration of 'std::unique_ptr<_Ty>::operator ='
2>          with
2>          [
2>              _Ty=dest::core::Tree::data
2>          ]
2>          This diagnostic occurred in the compiler generated function 'dest::core::Tree &dest::core::Tree::operator =(const dest::core::Tree &)'
2>  tree.cpp
2>  tester.cpp
2>  rect_io.cpp
2>  database_io.cpp
2>D:\Library\Dest\dest-0.8\inc\dest/io/database_io.h : warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss
2>  face_detector.cpp
2>  draw.cpp
2>  glob.cpp
2>  Generating Code...
2>
2>Build FAILED.
2>
2>Time Elapsed 00:00:11.21
3>------ Rebuild All started: Project: dest_gen_rects, Configuration: Debug Win32 ------
4>------ Rebuild All started: Project: dest_evaluate, Configuration: Debug Win32 ------
5>------ Rebuild All started: Project: dest_align, Configuration: Debug Win32 ------
6>------ Rebuild All started: Project: dest_tests, Configuration: Debug Win32 ------
7>------ Rebuild All started: Project: dest_track_video, Configuration: Debug Win32 ------
8>------ Rebuild All started: Project: dest_train, Configuration: Debug Win32 ------
3>Build started 3/29/2016 10:38:03 AM.
3>InitializeBuildStatus:
3>  Creating "dest_gen_rects.dir\Debug\dest_gen_rects.unsuccessfulbuild" because "AlwaysCreate" was specified.
4>Build started 3/29/2016 10:38:03 AM.
5>Build started 3/29/2016 10:38:03 AM.
6>Build started 3/29/2016 10:38:03 AM.
7>Build started 3/29/2016 10:38:03 AM.
4>InitializeBuildStatus:
4>  Creating "dest_evaluate.dir\Debug\dest_evaluate.unsuccessfulbuild" because "AlwaysCreate" was specified.
8>Build started 3/29/2016 10:38:03 AM.
5>InitializeBuildStatus:
5>  Creating "dest_align.dir\Debug\dest_align.unsuccessfulbuild" because "AlwaysCreate" was specified.
3>CustomBuild:
3>  Building Custom Rule D:/Library/Dest/dest-0.8/CMakeLists.txt
7>InitializeBuildStatus:
7>  Creating "dest_track_video.dir\Debug\dest_track_video.unsuccessfulbuild" because "AlwaysCreate" was specified.
4>CustomBuild:
4>  Building Custom Rule D:/Library/Dest/dest-0.8/CMakeLists.txt
8>InitializeBuildStatus:
8>  Creating "dest_train.dir\Debug\dest_train.unsuccessfulbuild" because "AlwaysCreate" was specified.
3>  CMake does not need to re-run because D:\Library\Dest Landmark\CMakeFiles\generate.stamp is up-to-date.
6>InitializeBuildStatus:
6>  Creating "dest_tests.dir\Debug\dest_tests.unsuccessfulbuild" because "AlwaysCreate" was specified.
5>CustomBuild:
5>  Building Custom Rule D:/Library/Dest/dest-0.8/CMakeLists.txt
7>CustomBuild:
7>  Building Custom Rule D:/Library/Dest/dest-0.8/CMakeLists.txt
4>  CMake does not need to re-run because D:\Library\Dest Landmark\CMakeFiles\generate.stamp is up-to-date.
5>  CMake does not need to re-run because D:\Library\Dest Landmark\CMakeFiles\generate.stamp is up-to-date.
7>  CMake does not need to re-run because D:\Library\Dest Landmark\CMakeFiles\generate.stamp is up-to-date.
6>CustomBuild:
6>  Building Custom Rule D:/Library/Dest/dest-0.8/CMakeLists.txt
8>CustomBuild:
8>  Building Custom Rule D:/Library/Dest/dest-0.8/CMakeLists.txt
8>  CMake does not need to re-run because D:\Library\Dest Landmark\CMakeFiles\generate.stamp is up-to-date.
6>  CMake does not need to re-run because D:\Library\Dest Landmark\CMakeFiles\generate.stamp is up-to-date.
3>ClCompile:
3>  dest_gen_rects.cpp
4>ClCompile:
4>  dest_evaluate.cpp
7>ClCompile:
7>  dest_track_video.cpp
5>ClCompile:
5>  dest_align.cpp
8>ClCompile:
8>  dest_train.cpp
6>ClCompile:
6>  test_transform.cpp
4>D:\Library\Dest\dest-0.8\inc\dest/io/database_io.h : warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss
7>D:\Library\Dest\dest-0.8\inc\dest/io/database_io.h : warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss
3>D:\Library\Dest\dest-0.8\inc\dest/io/database_io.h : warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss
3>D:\Library\Dest\dest-0.8\inc\dest/io/database_io.h : warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss
8>D:\Library\Dest\dest-0.8\inc\dest/io/database_io.h : warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss
8>D:\Library\Dest\dest-0.8\inc\dest/io/database_io.h : warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss
5>D:\Library\Dest\dest-0.8\inc\dest/io/database_io.h : warning C4819: The file contains a character that cannot be represented in the current code page (949). Save the file in Unicode format to prevent data loss
3>..\Dest\dest-0.8\examples\dest_gen_rects.cpp(23): fatal error C1083: Cannot open include file: 'opencv2/core/ocl.hpp': No such file or directory
3>
3>Build FAILED.
3>
3>Time Elapsed 00:00:01.58
4>LINK : fatal error LNK1104: cannot open file 'Debug\dest.lib'
5>LINK : fatal error LNK1104: cannot open file 'Debug\dest.lib'
4>
4>Build FAILED.
4>
4>Time Elapsed 00:00:02.22
5>
5>Build FAILED.
5>
5>Time Elapsed 00:00:02.21
8>LINK : fatal error LNK1104: cannot open file 'Debug\dest.lib'
8>
8>Build FAILED.
8>
8>Time Elapsed 00:00:02.59
7>LINK : fatal error LNK1104: cannot open file 'Debug\dest.lib'
7>
7>Build FAILED.
7>
7>Time Elapsed 00:00:02.95
6>  test_image.cpp
6>  test_shape.cpp
6>  test_matrix_io.cpp
6>  test_rect_io.cpp
6>  Generating Code...
6>LINK : fatal error LNK1104: cannot open file 'Debug\dest.lib'
6>
6>Build FAILED.
6>
6>Time Elapsed 00:00:06.94
9>------ Skipped Rebuild All: Project: ALL_BUILD, Configuration: Debug Win32 ------
9>Project not selected to build for this solution configuration 
========== Rebuild All: 1 succeeded, 7 failed, 1 skipped ==========

Can you please tell ma how can I fix it. 

Thank you.

**Comment by cheind** [comment]
Thanks for letting me know. Latest commit on master branch should resolve your issues.

**Comment by ghost** [comment]
Thank you for your response. 

But still I got an error even using latest commit on master branch. Its as follows. 

\Dest\dest-master\examples\dest_gen_rects.cpp(23): fatal error C1083: Cannot open include file: 'opencv2/core/ocl.hpp': No such file or directory

In opencv2.4.x there is separate DIR for ocl inside opencv2 include folder. 
Therefore i think it should be included as "#include <opencv2/ocl/ocl.hpp>". 
But, even after changing it  as "#include <opencv2/core/ocl.hpp>" to "#include <opencv2/ocl/ocl.hpp>" in opencv2.4.x version there is no member function called "setUseOpenCL", Actually it is in opencv3.x. 

In master branch it is suggested to compile with opencv2.4.x. I guess it works if it is compiled with opencv3.x (which i haven't tried). 

If it is possible please have a look once regarding above issue.
Thanks.

**Comment by cheind** [comment]
Thanks for noting, Totally forgot about the OCL issue. Will have a look

**Comment by cheind** [comment]
Should be resolved now. Could you test, please?

**Comment by ghost** [comment]
Yes, there are no more error. Thanks.

**Comment by cheind** [comment]
You are welcome.
